package config

import (
	"SNES_emulator/ui"
	"errors"
	"flag"
	"fmt"
	"io/fs"
	"log"
	"os"
	"path/filepath"
	"strings"
)

type EmulatorConfig struct {
	RomPath string

	PProf     bool
	PProfPath string

	ForceRegion string

	DisplayScale float64
	Inputs       InputDeviceMapping

	Shader string
}

func New() *EmulatorConfig {
	conf := &EmulatorConfig{}

	flag.BoolVar(&conf.PProf, "pp", false, "Enable performance profiling.")
	flag.StringVar(&conf.PProfPath, "ppp", "./.cpu.pprof", "The save path for the file generated by pprof.")
	flag.StringVar(&conf.ForceRegion, "force-region", "auto",
		"Forces \"PAL\" or \"NTSC\" emulation mode regardless of the rom header.")
	flag.Float64Var(&conf.DisplayScale, "ds", 1.5, "Sets the scaling factor for the display.")
	flag.Var(&conf.Inputs, "input",
		"Attaches the keyboard or any connected controller."+
			"\nControllers follow the ebitengine numbering scheme (0 and up)."+
			"\nUsage example: port0:keyboard,port1:controller0")
	flag.StringVar(&conf.Shader, "shader", "none",
		"Selects one of the built in Ebitengine/Kage shaders. Currently available options:"+
			"\n\"none\" - a simple bgr15 decoder"+
			"\n\"crt_basic\" - a crt shader")

	flag.Parse()

	flag.Usage = usage

	args := flag.Args()

	if len(args) < 1 {
		fmt.Println("Error: This app requires a ROM (.sfc) file to run.")
		flag.Usage()
		os.Exit(1)
	}

	if _, err := os.Stat(args[0]); errors.Is(err, fs.ErrNotExist) {
		fmt.Printf("Error: ROM (.sfc) file not found at %s\n", args[0])
		flag.Usage()
		os.Exit(1)
	}

	conf.RomPath = args[0]

	if conf.PProf {
		ext := filepath.Ext(conf.PProfPath)
		dir := filepath.Dir(conf.PProfPath)
		fid, err := os.Stat(dir)

		if ext != ".pprof" {
			fmt.Printf("Error: Invalid extension '%s', expected '.pprof'\n", ext)
			flag.Usage()
			os.Exit(1)
		}

		if err != nil {
			if errors.Is(err, fs.ErrNotExist) {
				fmt.Printf("Error: Directory '%s' does not exist\n", dir)
			} else {
				fmt.Printf("Error accessing path: %v\n", err)
			}
			flag.Usage()
			os.Exit(1)
		}

		if !fid.IsDir() {
			fmt.Printf("Error: '%s' is not a directory\n", dir)
			flag.Usage()
			os.Exit(1)
		}
	}

	return conf
}

func usage() {
	fmt.Fprintf(os.Stderr, "Usage: %s [options] <rom-path>\n", os.Args[0])
	fmt.Println("The list of all available [options]: ")
	flag.PrintDefaults()
}

func (ec *EmulatorConfig) GetInputMapping() []ui.SnesInput {
	return ec.Inputs.generateControllerTemplate()
}

func (ec *EmulatorConfig) GetDisplayScale() float64 {
	return ec.DisplayScale
}

func (ec *EmulatorConfig) IsPProfEnabled() bool {
	return ec.PProf
}

func (ec *EmulatorConfig) GetPProfPath() string {
	return ec.PProfPath
}

func (ec *EmulatorConfig) GetRomPath() string {
	return ec.RomPath
}

func (ec *EmulatorConfig) IsPal(isPalHeader func() bool) bool {
	if ec.ForceRegion == "PAL" {
		log.Println("Config: Forcing " + ec.ForceRegion + " mode.")
		return true
	}
	if ec.ForceRegion == "NTSC" {
		log.Println("Config: Forcing " + ec.ForceRegion + " mode.")
		return false
	}
	return isPalHeader()
}

func (ec *EmulatorConfig) GetSelectedShader() ui.Shader {
	var shader ui.Shader
	var err error

	//switch for easier future expansion
	switch strings.ToLower(ec.Shader) {
	case "crt_basic":
		shader, err = ui.NewCrtBasicShader()
	default:
		shader, err = ui.NewBgr15Shader()
	}

	if err != nil {
		panic(err)
	}
	return shader
}
