package config

import (
	"flag"
	"fmt"
	"os"
)

type EmulatorConfig struct {
	RomPath string

	PProf     bool
	PProfPath string
}

func New() *EmulatorConfig {
	conf := &EmulatorConfig{}

	flag.BoolVar(&conf.PProf, "pp", false, "Enable performance profiling.")
	flag.StringVar(&conf.PProfPath, "ppp", "./.cpu.pprof", "The save path for the file generated by pprof.")

	flag.Parse()

	flag.Usage = usage

	args := flag.Args()

	if len(args) < 1 {
		fmt.Println("Error: This app requires a ROM (.sfc) file to run.")
		flag.Usage()
		os.Exit(1)
	}

	if _, err := os.Stat(args[0]); os.IsNotExist(err) {
		fmt.Printf("Error: ROM (.sfc) file not found at %s\n", args[0])
		flag.Usage()
		os.Exit(1)
	}

	conf.RomPath = args[0]
	return conf
}

func usage() {
	fmt.Fprintf(os.Stderr, "Usage: %s [options] <rom-path>\n", os.Args[0])
	fmt.Println("The list of all available [options]: ")
	flag.PrintDefaults()
}

func (ec *EmulatorConfig) IsPProfEnabled() bool {
	return ec.PProf
}

func (ec *EmulatorConfig) GetPProfPath() string {
	return ec.PProfPath
}

func (ec *EmulatorConfig) GetRomPath() string {
	return ec.RomPath
}
